### PR TITLE
Rpc should handle other local apis too

### PR DESCRIPTION
**Pull request by cbotsikas**
The hardcoded check of ServiceDiscovery was blocking the Dashboard API.

Jira: WP-984

### CODE REVIEW

**Comment by aldafu** [comment]
Can you explain in more detail what this fixes?
How does RPC not handle local APIs?
I probably don't understand since I don't know what the dashboard code does.

**Comment by aldafu** [comment]
Are you okay with merging this instead? https://github.com/aldafu/webinos-jsonrpc2/commit/56c1201862417c79d30fbabde2434dbbe8302620

**Comment by cbotsikas** [comment]
Although i don't like the fact that we have hard coded reference to the "local" api's names (ServiceDescovery, Dashboard), we can merge your solution in order to unblock the Dashboard development.

We need something generic, in order to allow 3rd party developers to easily adapt webinos on their work. My regular expression was a temp solution aiming towards that direction. 

We need to reconsider the final check. I'm going to open a new Jira issue for that future work.

**Comment by aldafu** [comment]
I agree, it's really a quick measure to get people started with the dashboard. Closing this request then.

**Pull request closed without merging**
